final List<String> summary = [
  'assets/img/solar_system.png',
  'Sistema Solar',
  'A vida como a conhecemos',

  '   Localizado em um braço espiral externo da Via Láctea, nosso sistema planetário, o Sistema Solar é o conjunto formado pelo Sol, a estrela central e maior componente do sistema solar que tem mais de 99,85% da massa total do sistema, e os corpos celestes que estão sob seu domínio gravitacional.',

  '   Nosso sistema solar consiste em nossa estrela, o Sol, e tudo o que é atraído por sua gravidade - os planetas Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno, planetas anões como Plutão, dezenas de luas e milhões de asteróides, cometas e meteoróides. Além do nosso próprio sistema solar, descobrimos milhares de sistemas planetários orbitando outras estrelas na Via Láctea. Nosso sistema solar é o único ue conhecemos que abriga vida, e quanto mais exploramos, mais encontramos potencial para a vida dentro dele. Tanto a lua de Júpiter, Europa quanto a lua de Saturno, Enceladus, têm oceanos globais de água salgada sob conchas espessas e geladas.',

  '   O sistema solar se estende a muito além dos oito planetas que orbitam o Sol, também inclui o Cinturão de Kuiper, que fica além da órbita de Netuno, um anel pouco ocupado de corpos gelados, quase todos menores que o mais popular Objeto do Cinturão de Kuiper, Plutão o planeta anão.\n\n    E além das margens do cinturão de Kuiper está a Nuvem de Oort, que nunca foi observado diretamente, mas sua existência é prevista com base em modelos matemáticos e observações de cometas que provavelmente se originam lá. Feita de pedaços gelados de detritos espaciais do tamanho de montanhas e, às vezes, maiores, orbitando nosso Sol a 1,6 anos-luz de distância, a Nuvem de Oort se estende de 5.000 unidades astronômicas para 100.000 unidades astronômicas. Uma unidade astronômica (ou AU) equivale a distância entre o Sol e a Terra, ou seja, 150 milhões de quilômetros. A Nuvem de Oort é o limite da influência gravitacional do Sol, onde objetos em órbita podem se virar e voltar mais perto do nosso Sol.\n\n   A heliosfera do Sol não se estende tão longe. A heliosfera é a bolha criada pelo vento solar - uma corrente de gás eletricamente carregado soprando para fora do Sol em todas as direções. O limite onde o vento solar é abruptamente abrandado pela pressão dos gases interestelares é chamado choque de terminação. Essa aresta ocorre entre 80-100 unidades astronômicas. Duas sondas da NASA, lançado em 1977, cruzou o choque de terminação: Voyager 1 em 2004 e Voyager 2 em 2007. Mas vai ser muitos milhares de anos antes que as duas Voyagers saiam da Nuvem de Oort.',

  '   O sistema solar se formou cerca de 4,5 bilhões de anos atrás, a partir de uma densa nuvem de gás e poeira interestelar. A nuvem entrou em colapso, possivelmente devido a uma onda de choque de uma estrela explosiva próxima, uma supernova. Quando essa nuvem de poeira desabou, formou uma nebulosa solar - um disco giratório e rodopiante de material.\n\n   No centro, a gravidade atraía cada vez mais material. Eventualmente, a pressão no núcleo era tão grande que os átomos de hidrogênio começaram a se combinar e formar hélio, liberando uma tremenda quantidade de energia. Com isso, nosso Sol nasceu e acabou acumulando mais de 99% da matéria disponível.\n\n   A matéria mais distante do disco também estava se aglomerando. Esses aglomerados se chocaram, formando objetos cada vez maiores. Alguns deles cresceram grandes o suficiente para que sua gravidade os transformasse em esferas, tornando-se planetas, planetas anões e grandes luas. Em outros casos, os planetas não se formaram: o cinturão de asteróides é constituído por pedaços do sistema solar inicial que nunca poderiam se unir em um planeta. Outras sobras menores se tornaram asteróides, cometas, meteoróides e pequenas luas irregulares.',

  '   A ordem e o arranjo dos planetas e outros corpos em nosso sistema solar se devem à forma como o sistema solar se formou. Mais próximo do Sol, apenas materiais rochosos podiam suportar o calor quando o sistema solar era jovem. Por esse motivo, os quatro primeiros planetas - Mercúrio, Vênus, Terra e Marte - são planetas rochosos. Eles são relativamente pequenos, com superfícies sólidas e rochosas. Enquanto isso, materiais que estamos acostumados a ver como gelo, líquido ou gás se depositam nas regiões externas do jovem sistema solar. A gravidade juntou esses materiais, e é aí que encontramos os gigantes de gás Júpiter e Saturno e os gigantes de gelo Urano e Netuno.',

  '   Existem mais de 150 luas conhecidas em nosso sistema solar e várias outras aguardando confirmação da descoberta. Dos oito planetas, Mercúrio e Vênus são os únicos sem luas. Os planetas gigantes capturam mais luas. Júpiter e Saturno lideram há muito a contagem de luas do nosso sistema solar. De certa forma, os enxames de luas ao redor desses mundos se assemelham a mini versões do nosso sistema solar. Plutão, menor que a nossa própria lua, tem cinco luas em sua órbita, incluindo o Caronte, uma lua tão grande que faz Plutão oscilar. Até pequenos asteróides podem ter luas. Em 2017, os cientistas descobriram que o asteróide 3122 Florence tinha duas pequenas luas.',

  'assets/pictures/solar_system.jpg'
];